version: "3.0"

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: equisplit
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 3
    expose:
      - "5432"
    ports:
      - "5432:5432"

  equisplit:
    container_name: equisplit
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
